import { Film } from './film';

export const  FILMS: Film[]= [
    {
      id:10,
      categoryId:1,
      name: 'Мама',
      price: 150,
      description: 'дфоило',
      rating:'4.9',
      originalLink:'',
      images: '',
      categoryName:'Ужастики',
      viewCount: 0,
    },
    {
      id:11,
      categoryId:1,
      name: 'Зомби',
      price: 5,
      description: 'лфырвлф',
      rating:'4.9',
      originalLink:'',
      images: 'https://cdn.f.kz/prod/1062/1061595_550.jpg',
      categoryName:'Ужастики',    
      viewCount: 0,
    },
    {
      id:12,
      categoryId:1,
      name: 'ВААА',
      price: 10,
      description: 'лфыроалои',
      rating:'4.9',
      originalLink:'',
      images: 'https://cdn.f.kz/prod/1062/1061595_550.jpg',
      categoryName:'Ужастики',
      viewCount: 0,  
    },
    {
      id:20,
      categoryId:2,
      name: 'дфвоаи',
      price: 100,
      description: 'вбоис',
      rating:'4.9',
      originalLink:'',
      images: 'https://cdn.f.kz/prod/1062/1061595_550.jpg',
      categoryName:'Комедия',
      viewCount: 0,   
    },
    {
      id:21,
      categoryId:2,
      name: 'ФФФ',
      price: 0,
      description: 'фвладфиу',
      rating:'4.9',
      originalLink:'',
      images: 'https://cdn.f.kz/prod/1062/1061595_550.jpg',
      categoryName:'Комедия',    
      viewCount: 0,
    },
    {
      id:30,
      categoryId:3,
      name: 'ФФФ',
      price: 0,
      description: 'фвладфиу',
      rating:'4.9',
      originalLink:'',
      images: 'https://cdn.f.kz/prod/1062/1061595_550.jpg',
      categoryName:'Мелодрамма',    
      viewCount: 0,
    },
    {
      id:31,
      categoryId:3,
      name: 'ФФФ',
      price: 0,
      description: 'фвладфиу',
      rating:'4.9',
      originalLink:'',
      images: 'https://cdn.f.kz/prod/1062/1061595_550.jpg',
      categoryName:'Мелодрамма',
      viewCount: 0,    
    },
    {
      id:40,
      categoryId:4,
      name: 'ФФФ',
      price: 0,
      description: 'фвладфиу',
      rating:'4.9',
      originalLink:'',
      images: 'https://cdn.f.kz/prod/1062/1061595_550.jpg',
      categoryName:'Документальные',
      viewCount: 0,    
    },
    
    
  ];

